version: 2.1
workflows:
  analyze:
    jobs:
      - deploy_to_pypi

jobs:
  deploy_to_pypi:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Liste les fichiers du dépots
          command: |
            - ls

      - run:
          name: install dependencies
          command: |
            git clone https://github.com/lyvd/bandit4mal.git
            python -m venv venv
            . venv/bin/activate
            cd bandit4mal
            python setup.py install
            cd ..
            pip install -q -r requirements.txt  requests PyGithub
            python banditController.py --configure
            pip install -q -r requirements-pentest.txt

      - run:
          name: Start analyze
          command: |
            . venv/bin/activate
            python banditController.py --start
